
name: Publish to pub.dev

on:
  push:
    tags:
      - 'upgrade-[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: '>> Flutter plugin <<'
        uses: k-paxian/dart-package-publisher@master
          with:
            accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
            refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
